# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Good Girl Gone Tech'
tagline:          'The journey of Katie Rovani taking over the world.'
description:      'A brazen mother of two that pairs her driving passion of Operations with an ever-present desire to learn more.'
url:              http://gggt.rovani.net
baseurl:          /

author:
  name:           'Katie Rovani'
  url:            https://twitter.com/cajunmericle

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Good-Girl-Gone-Tech/Good-Girl-Gone-Tech.github.io
